### PR TITLE
show full paths flag

### LINKED ISSUE #813: Output full paths to files with errors
Some tools, such as IntelliJ, can index file paths within the console. Unfortunately, this requires outputting the full path to the files. Here's what it looks like:
demo

I can somehow get around this and change the output of lint command, but then the highlighting is lost and everything is displayed incorrectly. I would like to have a separate flag for this output

### PR DESCRIPTION
**Pull request by Marat-Tim**
close #813

### CODE REVIEW

File: cmd/lint_cmd.go [hunk 1]
```diff
@@ -65,6 +65,7 @@ func GetLintCommand() *cobra.Command {
 	cmd.Flags().String("globbed-files", "", "Glob pattern of files to lint")
 	cmd.Flags().Bool("fix", false, "Apply auto-fixes for rules that support it")
 	cmd.Flags().String("fix-file", "", "Write fixes to specified file instead of overwriting original")
+	cmd.Flags().BoolP("abs-paths", "y", false, "Output absolute paths")
```
Comment (daveshanley) [inline cmd/lint_cmd.go]: Would you be able to remove the shortcode? we have already run out and I want to save the last few remaining letters for super important stuff :)

**Comment by Marat-Tim** [comment]
@daveshanley
